  name: 'Run Parasoft SOAtest'
  description: 'A GitHub Action for running functional tests with Parasoft SOAtest and reviewing results directly in GitHub.'
  author: 'Parasoft'
  branding:
    icon: 'aperture'
    color: 'blue'
  inputs:
    installDir:
      description: 'Installation folder of Parasoft SOAtest. If not specified, the soatestcli executable must be added to PATH.'
      required: false
    workingDir:
      description: 'Working directory for running SOAtest.'
      required: false
      default: ${{ github.workspace }}
    testConfig:
      description: 'Test configuration to be used for test execution.'
      required: false
      default: 'user://Example Configuration'
    resource:
      description: 'The path to the test suite(s) relative to the workspace.'
      required: false
      default: 'TestAssets'
    settings:
      description: 'Setting file used to configure execution preferences.'
      required: false
    reportDir:
      description: 'Output folder for reports from test execution.'
      required: false
      default: 'reports'
    reportFormat:
      description: 'Format of reports from test execution.'
      required: false
      default: 'xml,html'
    environment:
      description: 'Name of the SOAtest environment to use for executing the tests.'
      required: false
    additionalParams:
      description: 'Additional parameters for the soatestcli executable.'
      required: false
  runs:
    using: node16
    main: 'dist/index.js'